# Generated by Django 5.0.6 on 2025-06-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_timeentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_type',
            field=models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Rate')], default='hourly', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='fixed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
