# Generated by Django 5.0.6 on 2025-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_project_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
