# Generated by Django 5.2.3 on 2025-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_description_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
