# Generated by Django 5.2.3 on 2025-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_client_remove_project_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
