# Generated by Django 5.0.6 on 2025-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_timeentry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
