# Generated by Django 5.2.3 on 2025-06-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_project_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
