# Generated by Django 5.2.3 on 2025-06-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_invoice_amount_due_remove_invoice_total_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='description',
            new_name='notes',
        ),
    ]
