# Generated by Django 5.2.3 on 2025-06-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='time_entries',
            field=models.ManyToManyField(to='tracker.timeentry'),
        ),
    ]
