# Generated by Django 5.2.3 on 2025-06-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_invoice_time_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='time_entries',
        ),
    ]
