# Generated by Django 5.2.3 on 2025-06-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_invoice_time_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.invoice'),
        ),
    ]
