# Generated by Django 5.2.3 on 2025-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_timeentry_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
