# Generated by Django 6.0.4 on 2026-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='take_home_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as a percentage (e.g. 10 for 10%)', max_digits=5),
        ),
    ]
